- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardview.jsp
- Project/src/main/webapp/css/post.css
> 게시판 좋아요 버튼 추가

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardlist.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardview.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardwrite.jsp
- Project/src/main/webapp/css/boardwrite.css
- Project/src/main/webapp/css/sidebar.css
- Project/src/main/webapp/css/style.css
> 공통디자인 수정,게시판,게시글 작성 페이지 수정,사이드바 수정

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/like/like.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/like/likebox.jsp
> 7월 7일 LIke DB까지 연결한버전

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/mypage/mypage.jsp
- Project/src/main/webapp/common/header.jsp
- Project/src/main/webapp/css/header.css
> header 변경 선택자변경

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardlist.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/home.jsp
- Project/src/main/webapp/common/header.jsp
- Project/src/main/webapp/css/boardlist.css
- Project/src/main/webapp/css/footer.css
- Project/src/main/webapp/css/home.css
> boardlist jsp css , header 수정

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardlist.jsp
- Project/src/main/webapp/css/boardview.css
> 댓글등록버튼 수정,인기게시글 상단표시

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardview.jsp
> 7월 8일 10시19분

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardview.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/member/login.jsp
- Project/src/main/webapp/common/header2.jsp
좋아요 기능 복구 완료 
메인페이지에서 회원가입 => 누르면 이상한대로가지던 링크 해결 및 회원가입누르면 바로 회원가입 UI로 가게 수정
> 2025년 7월 8일 오전 10시 41분

- Project/src/main/java/egovframework/example/board/service/BoardService.java
- Project/src/main/java/egovframework/example/board/service/impl/BoardMapper.java
- Project/src/main/java/egovframework/example/board/service/impl/BoardServiceImpl.java
- Project/src/main/java/egovframework/example/board/web/BoardController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/Board.xml
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardlist.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardview.jsp
- Project/src/main/webapp/css/boardview.css
인기게시글 수정완료
댓글 수정/삭제 기능 추가 
사진 나오게 구현 완료
> 2025년 7월 8일 수정본 

- Project/src/main/java/egovframework/example/member/service/impl/MemberServiceImpl.java
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardview.jsp
> 25년 7월 8일 좋아요 안보이던거 수정

- Project/src/main/java/egovframework/example/board/service/BoardVO.java
- Project/src/main/java/egovframework/example/board/web/BoardController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/Board.xml
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardlist.jsp
>  카테고리별 검색기능 추가

- Project/src/main/webapp/common/header2.jsp
- Project/src/main/webapp/common/sidebar.jsp
> 글씨 크기 수정 및 사이드바 내용 간결히

- Project/src/main/resources/egovframework/sqlmap/example/mappers/Board.xml
> 게시글 작성 순서대로 앞에가도록 수정

- Project/src/main/java/egovframework/example/board/service/BoardVO.java
- Project/src/main/java/egovframework/example/mypage/service/MypageLikeVO.java
- Project/src/main/java/egovframework/example/mypage/service/MypageMyPostVO.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/Board.xml
- Project/src/main/resources/egovframework/sqlmap/example/mappers/MypageMapper.xml
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardlist.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/mypage/mypage.jsp
- Project/src/main/webapp/css/style.css
게시판 마이페이지 조회수 옆에 좋아요 수 나오게 수정 
25년 7월 9일
> 게시판 마이페이지 조회수 옆에 좋아요 수 나오게 수정 

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/mypage/mypage.jsp
- Project/src/main/webapp/common/header.jsp
- Project/src/main/webapp/common/header2.jsp
- Project/src/main/webapp/css/header.css
- Project/src/main/webapp/css/header2.css
- Project/src/main/webapp/css/mypage.css
> 헤더 마이페이지 css 수정

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardlist.jsp
- Project/src/main/webapp/css/pagination.css
> boardlist 페이징수정

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/member/login.jsp
> 슬라이드 시간 수정

- Project/src/main/webapp/common/sidebar.jsp
> 사이드바 마이페이지 외엔 내정보수정 안뜨게

- Project/src/main/java/egovframework/example/mypage/service/MypageService.java
- Project/src/main/java/egovframework/example/mypage/service/impl/MypageMapper.java
- Project/src/main/java/egovframework/example/mypage/service/impl/MypageServiceImpl.java
- Project/src/main/java/egovframework/example/mypage/web/MypageController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/MypageMapper.xml
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/mypage/mypage.jsp
> 마이페이지 페이지네이션 완료 및 탭페이지 오류 처리

- Project/src/main/webapp/common/header.jsp
- Project/src/main/webapp/css/header.css
> 글쓰기에서 돋보기버튼크기조정

- Project/src/main/webapp/WEB-INF/config/egovframework/springmvc/dispatcher-servlet.xml
> 파일 크기 코드수정

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardupdate.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardwrite.jsp
- Project/src/main/webapp/css/boardupdate.css
- Project/src/main/webapp/css/boardview.css
- Project/src/main/webapp/css/boardwrite.css
> 사진 미리보기 삭제버튼

- Project/src/main/java/egovframework/example/board/web/BoardController.java
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardview.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardwrite.jsp
- Project/src/main/webapp/css/boardview.css
> 순번 자동 출력 코드 추가

- Project/src/main/java/egovframework/example/board/service/impl/BoardMapper.java
- Project/src/main/java/egovframework/example/board/service/impl/BoardServiceImpl.java
- Project/src/main/java/egovframework/example/file/service/FileService.java
- Project/src/main/java/egovframework/example/file/service/impl/FileMapper.java
- Project/src/main/java/egovframework/example/file/service/impl/FileServiceImpl.java
- Project/src/main/java/egovframework/example/like/service/LikeService.java
- Project/src/main/java/egovframework/example/like/service/impl/LikeMapper.java
- Project/src/main/java/egovframework/example/like/service/impl/LikeServiceImpl.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/Board.xml
- Project/src/main/resources/egovframework/sqlmap/example/mappers/FileMapper.xml
- Project/src/main/resources/egovframework/sqlmap/example/mappers/LikeMapper.xml
> 게시글 삭제 기능 수정

- Project/src/main/java/egovframework/example/common/interceptor/LoginInterceptor.java
- Project/src/main/java/egovframework/example/member/web/MemberController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/Member.xml
- Project/src/main/webapp/WEB-INF/config/egovframework/springmvc/dispatcher-servlet.xml
- Project/src/main/webapp/common/header.jsp
- Project/src/main/webapp/common/sidebar.jsp
> 인터셉터 설정 및 로그인 로그아웃 페이지 리다이렉트

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardupdate.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardwrite.jsp
- Project/src/main/webapp/css/boardupdate.css
- Project/src/main/webapp/css/boardwrite.css
> 버튼선택자변경 및 그림자 수정

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardupdate.jsp
- Project/src/main/webapp/css/boardupdate.css
> 게시판수정 버튼 문제해결

- Project/src/main/webapp/common/sidebar.jsp
- Project/src/main/webapp/css/header.css
- Project/src/main/webapp/css/sidebar.css
- Project/src/main/webapp/css/style.css
> 로그인버튼 선택자 조정 공통스타일 버튼태그삭제 반응형겹치는현상문제해결

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardlist.jsp
- Project/src/main/webapp/common/header.jsp
- Project/src/main/webapp/common/header2.jsp
- Project/src/main/webapp/css/boardlist.css
> 전체 탭 관련 수정(헤더, 연결 링크 등)

- Project/src/main/java/egovframework/example/common/interceptor/LoginInterceptor.java
- Project/src/main/java/egovframework/example/data/service/impl/DataWF.java
- Project/src/main/webapp/WEB-INF/config/egovframework/springmvc/dispatcher-servlet.xml
> 인터셉터 수정 및 번역필터 강화

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardview.jsp
- Project/src/main/webapp/css/header2.css
> 상세조회 코드 추가

- Project/src/main/java/egovframework/example/datako/service/DataKOVO.java
- Project/src/main/java/egovframework/example/datako/service/impl/DataKOServiceImpl.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/DataKOMapper.xml
> 한식 api 마무리

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/mypage/mypage.jsp
- Project/src/main/webapp/css/mypage.css
> 마이페이지에 좋아요한 레시피조회 추가

- Project/src/main/java/egovframework/example/board/service/BoardService.java
- Project/src/main/java/egovframework/example/board/service/impl/BoardMapper.java
- Project/src/main/java/egovframework/example/board/service/impl/BoardServiceImpl.java
- Project/src/main/java/egovframework/example/board/web/BoardController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/Board.xml
> 게시판 카테고리별 인기게시글 조회기능

- Project/src/main/java/egovframework/example/data/service/impl/SpoonacularService.java
- Project/src/main/java/egovframework/example/member/service/MemberService.java
- Project/src/main/java/egovframework/example/member/service/impl/MemberMapper.java
- Project/src/main/java/egovframework/example/member/service/impl/MemberServiceImpl.java
- Project/src/main/java/egovframework/example/member/web/MemberController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/Member.xml
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/mypage/mycorrection.jsp
> 회원 탈퇴 기능 구현

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/member/login.jsp
> 회원 가입시 아이디 양식 변경

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipeView.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipelist.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipeview.jsp
- Project/src/main/webapp/common/header.jsp
> header 영어 한글 간격, recipelist 임시템플릿추가

- Project/src/main/java/egovframework/example/recipe/service/RecipeService.java
- Project/src/main/java/egovframework/example/recipe/service/RecipeVO.java
- Project/src/main/java/egovframework/example/recipe/service/impl/RecipeMapper.java
- Project/src/main/java/egovframework/example/recipe/service/impl/RecipeServiceImpl.java
- Project/src/main/java/egovframework/example/recipe/web/RecipeController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/RecipeMapper.xml
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipeView.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipelist.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipeview.jsp
> 레시피 api 전체조회,상세조회 만듬

- Project/src/main/java/egovframework/example/member/service/MemberVO.java
- Project/src/main/java/egovframework/example/member/service/impl/MemberMapper.java
- Project/src/main/java/egovframework/example/member/service/impl/MemberServiceImpl.java
- Project/src/main/java/egovframework/example/member/web/MemberController.java
- Project/src/main/java/egovframework/example/mypage/web/MypageController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/Member.xml
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/member/redirectConfirm.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/mypage/mycorrection.jsp
> 임시비밀번호 회원 DB설정

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipelist.jsp
> recipelist 탭전환문제 해결

- Project/src/main/java/egovframework/example/recipe/service/RecipeService.java
- Project/src/main/java/egovframework/example/recipe/service/impl/RecipeMapper.java
- Project/src/main/java/egovframework/example/recipe/service/impl/RecipeServiceImpl.java
- Project/src/main/java/egovframework/example/recipe/web/RecipeController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/RecipeMapper.xml
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipelist.jsp
> 레시피페이지 전체 탭별 모두 페이징완료

- Project/src/main/webapp/common/header.jsp
> 헤더 레시피 버튼 수정

- Project/bin/src/main/webapp/css/style.css
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardlist.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/home.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/member/login.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipelist.jsp
- Project/src/main/webapp/common/header.jsp
- Project/src/main/webapp/common/header2.jsp
- Project/src/main/webapp/css/header2.css
- Project/src/main/webapp/css/home.css
- Project/src/main/webapp/css/login.css
- Project/src/main/webapp/css/style.css
> css 폰트 수정 및 간격 등 기타 조정

- Project/src/main/java/egovframework/example/HomeController.java
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/home.jsp
- Project/src/main/webapp/css/boardview.css
> 홈jsp 컨트롤러 수정

- Project/src/main/webapp/common/footer.jsp
- Project/src/main/webapp/css/footer.css
- Project/src/main/webapp/css/pagination.css
> 꼬리말 본문 간격조정+맨위로 버튼생성

- Project/src/main/java/egovframework/example/like/service/LikeService.java
- Project/src/main/java/egovframework/example/like/service/impl/LikeServiceImpl.java
- Project/src/main/java/egovframework/example/like/web/LikeController.java
> 좋아요 최종최종수정

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/board/boardview.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipeView.jsp
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/recipe/recipeview.jsp
> boardview 꼬리말 수정, recipeview.jsp 정리

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/mypage/mypage.jsp
> 마이페이지 약간수정

- Project/src/main/java/egovframework/example/member/service/MemberService.java
- Project/src/main/java/egovframework/example/member/service/MemberVO.java
- Project/src/main/java/egovframework/example/member/service/impl/MemberMapper.java
- Project/src/main/java/egovframework/example/member/service/impl/MemberServiceImpl.java
- Project/src/main/java/egovframework/example/member/web/MemberController.java
- Project/src/main/resources/egovframework/sqlmap/example/mappers/Member.xml
- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/mypage/mycorrection.jsp
> 카카오 회원 내정보수정 디버깅

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/event/test.jsp
- Project/src/main/webapp/css/test.css
> 테스트 완성 (남은 질문수 바,텍스트)

- Project/src/main/webapp/WEB-INF/jsp/egovframework/example/home.jsp
- Project/src/main/webapp/css/header2.css
- Project/src/main/webapp/css/home.css
> 모바일 반응형 수정

- Project/src/main/webapp/common/header.jsp
> 레시피 이벤트 탭 주석처리

- Project/src/main/java/egovframework/example/board/web/BoardController.java
- Project/src/main/java/egovframework/example/file/service/FileService.java
- Project/src/main/java/egovframework/example/file/service/impl/FileServiceImpl.java
- Project/src/main/java/egovframework/example/file/web/FileController.java
> 댓글,파일 관련코드 설명 주석달기

- Project/src/main/webapp/css/home.css
> 홈화면 내 이동 부호 위치 수정
